name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true  # Ensure LFS files are downloaded

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Ensure Python version matches your local environment

    # Cache dependencies (optional for speeding up installs)
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Debug paths and check for necessary files
    - name: Debug paths and file existence
      run: |
        echo "Current working directory: $(pwd)"
        echo "Listing all files:"
        ls -R
        echo "Checking if data file exists:"
        test -f data/housing.csv && echo "data/housing.csv exists" || echo "data/housing.csv is missing"
        echo "Checking if model file exists:"
        test -f model/housing_price_model.joblib && echo "model file exists" || echo "model file is missing"

    # Run tests
    - name: Run tests
      run: pytest tests --disable-warnings

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test  # Run only if the "test" job succeeds

    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t shubhamaute1/housepriceprediction:latest .

    # Push Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push shubhamaute1/housepriceprediction:latest

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test  # Run only if the "test" job succeeds

    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t shubhamaute1/housepriceprediction:latest .

   
    - name: Push Docker image
      run: |
        docker push shubhamaute1/housepriceprediction:latest